name: Check & test & build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Quality & security checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - name: Check out code
        uses: actions/checkout@v3

      # - name: Lint Go Code
      #   run: make check

  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Run Pocketbase
        run: |
          make serve &
          sleep 3

      - name: Run unit tests with
        run: make test
